<div class="button-pratinjau-laporan d-md-flex justify-content-md-end" id="button-pratinjau">
    <a href="/laporanAMI-pdf-cover" target="_blank"><button class="btn btn-primary mt-3">Pratinjau</button></a>
</div>
<br>
<nav>
    <div class="nav nav-tabs tabs-laporanAMI d-flex" id="nav-tab" role="tablist">
        <div class="row">
            <button class="col nav-link tab-laporantindaklanjutami {{ Request::routeIs('laporan.spm.laporan.audit.mutu.internal') ? 'active' : '' }}" id="nav-tindaklanjut-cover" data-bs-toggle="tab" data-bs-target="#nav-tindaklanjut-cover" type="button" role="tab" aria-controls="nav-home" aria-selected="true"><a href="/laporan-spm-laporan-audit-mutu-internal">Cover</a></button>
            <button class="col nav-link tab-laporantindaklanjutami {{ Request::routeIs('laporan.spm.laporan.audit.mutu.internal.daftarisi') ? 'active' : '' || Request::routeIs('laporan.spm.laporan.audit.mutu.internal.editdaftarisi') ? 'active' : '' }}" id="nav-tindaklanjut-daftarisi" data-bs-toggle="tab" data-bs-target="#nav-tindaklanjut-daftarisi" type="button" role="tab" aria-controls="nav-profile" aria-selected="false"><a href="/laporan-spm-laporan-audit-mutu-internal-daftarisi">Daftar Isi</a></button>
            <button class="col nav-link tab-laporantindaklanjutami {{ Request::routeIs('laporan.spm.laporan.audit.mutu.internal.katapengantar') ? 'active' : '' || Request::routeIs('laporan.spm.laporan.audit.mutu.internal.editkatapengantar') ? 'active' : '' }}" id="nav-tindaklanjut-katapengantar" data-bs-toggle="tab" data-bs-target="#nav-tindaklanjut-katapengantar" type="button" role="tab" aria-controls="nav-contact" aria-selected="false"><a href="/laporan-spm-laporan-audit-mutu-internal-katapengantar">Kata Pengantar</a></button>
            <button class="col nav-link tab-laporantindaklanjutami {{ Request::routeIs('laporan.spm.laporan.audit.mutu.internal.pendahuluan') ? 'active' : '' || Request::routeIs('laporan.spm.laporan.audit.mutu.internal.editpendahuluan') ? 'active' : '' }}" id="nav-tindaklanjut-pendahuluan" data-bs-toggle="tab" data-bs-target="#nav-tindaklanjut-pendahuluan" type="button" role="tab" aria-controls="nav-contact" aria-selected="false"><a href="/laporan-spm-laporan-audit-mutu-internal-pendahuluan">Pendahuluan</a></button>
            <button class="col nav-link tab-laporantindaklanjutami {{ Request::routeIs('laporan.spm.laporan.audit.mutu.internal.tujuanaudit') ? 'active' : '' || Request::routeIs('laporan.spm.laporan.audit.mutu.internal.tujuanaudit') ? 'active' : '' }}" id="nav-tindaklanjut-tujuanaudit" data-bs-toggle="tab" data-bs-target="#nav-tindaklanjut-tujuanami" type="button" role="tab" aria-controls="nav-contact" aria-selected="false"><a href="/laporan-spm-laporan-audit-mutu-internal-tujuanaudit">Tujuan AMI</a></button>
            <button class="col nav-link tab-laporantindaklanjutami {{ Request::routeIs('laporan.spm.laporan.audit.mutu.internal.lingkupaudit') ? 'active' : '' || Request::routeIs('laporan.spm.laporan.audit.mutu.internal.lingkupaudit') ? 'active' : '' }}" id="nav-tindaklanjut-lingkupaudit" data-bs-toggle="tab" data-bs-target="#nav-tindaklanjut-ruanglingkupami" type="button" role="tab" aria-controls="nav-contact" aria-selected="false"><a href="/laporan-spm-laporan-audit-mutu-internal-lingkupaudit">Ruang Lingkup AMI</a></button>
            <button class="col nav-link tab-laporantindaklanjutami {{ Request::routeIs('laporan.spm.laporan.audit.mutu.internal.jadwalaudit') ? 'active' : '' }}" id="nav-tindaklanjut-jadwalaudit" data-bs-toggle="tab" data-bs-target="#nav-tindaklanjut-statusptkami" type="button" role="tab" aria-controls="nav-contact" aria-selected="false"><a href="/laporan-spm-laporan-audit-mutu-internal-jadwalaudit">Status PTK AMI</a></button>
            <button class="col nav-link tab-laporantindaklanjutami {{ Request::routeIs('laporan.spm.laporan.audit.mutu.internal.temuanpositif') ? 'active' : '' || Request::routeIs('laporan.spm.laporan.audit.mutu.internal.temuanpositif') ? 'active' : '' }}" id="nav-tindaklanjut-temuanpositif" data-bs-toggle="tab" data-bs-target="#nav-tindaklanjut-kesimpulan" type="button" role="tab" aria-controls="nav-contact" aria-selected="false"><a href="/laporan-spm-laporan-audit-mutu-internal-temuanpositif">Kesimpulan</a></button>
        </div>
    </div>
</nav>